function hello_world(~,~)
% HELL0_WORLD  Traditional programming demonstration.

%   Copyright 2016-2017 Cleve Moler
%   Copyright 2016-2017 The MathWorks, Inc.

hello_string = 'Hello World';
hello_position = [.75*rand .90*rand .25 .10];
hello_button = uicontrol( ...
   'string',hello_string, ...
   'style','pushbutton', ...
   'units','normalized', ...
   'position',hello_position, ...
   'fontsize',16, ...
   'callback',@hello_world); 
end
