function logo_wave(~)
% LOGO_WAVE   Vibrating L-shaped membrane.

%   Copyright 2016-2017 Cleve Moler
%   Copyright 2016-2017 The MathWorks, Inc.

persistent L mu
if isempty(L)
   L{1} = 30*membrane(1,25);
   L{2} = 2*membrane(2,25);
   L{3} = -2*membrane(3,25);
   L{4} = 5*membrane(4,25);
   L{5} = -3*membrane(5,25);
   L{6} = 4*membrane(6,25);
   mu = sqrt([9.6397238445, 15.19725192, 2*pi^2, ...
             29.5214811, 31.9126360, 41.4745099]);
end

thumb = nargin > 0;
S = initialize_graphics(thumb);

while pawsit(thumb)
   t = pi*labtime/mu(1);
   Z = cos(mu(1)*t)*L{1} + sin(mu(2)*t)*L{2} + sin(mu(3)*t)*L{3} +  ...
       sin(mu(4)*t)*L{4} + sin(mu(5)*t)*L{5} + sin(mu(6)*t)*L{6};
   set(S,'zdata',Z)
   drawnow
end

finalize_graphics(thumb)

% ------------------------------------------------------

    function S = initialize_graphics(thumb)
        if thumb
            cla
        else
            clf
            shg
            set(gcf,'name','logo_wave', ...
                'menu','none', ...
                'numbertitle','off');
            axes('pos',[.125 .25 .75 .5], ...
                'xtick',[],'ytick',[], ...
                'box','on');
            axes
            uicontrol('style','pushbutton', ...
              'units','normalized', ...
              'position',[.90 .92 .08 .06], ...
              'string','info', ...
              'fontweight','bold', ...
              'background','white', ...
              'callback', ...
                  'web(''info/logo_wave_info.html'',''-notoolbar'')');
        end
        set(gca, ...
             'CameraPosition', [-193.4013 -265.1546  220.4819],...
             'CameraTarget',[26 26 10], ...
             'CameraUpVector',[0 0 1], ...
             'CameraViewAngle',9.5, ...
             'DataAspectRatio', [1 1 .9],...
             'Visible','off', ...
             'XLim',[1 51], ...
             'YLim',[1 51], ...
             'ZLim',[-10 40]);
        S = surface(L{1}, ...
             'EdgeColor','none', ...
             'FaceColor',[0.9 0.2 0.2], ...
             'FaceLighting','phong', ...
             'AmbientStrength',0.3, ...
             'DiffuseStrength',0.6, ... 
             'Clipping','off',...
             'BackFaceLighting','lit', ...
             'SpecularStrength',1.0, ...
             'SpecularColorReflectance',1, ...
             'SpecularExponent',7);
        light('Position',[40 100 20], ...
             'Style','local', ...
             'Color',[0 0.8 0.8]);
        light('Position',[.5 -1 .4], ...
             'Color',[0.8 0.8 0]);
    end
 
    function t = labtime
    % LABTIME  Current time, in seconds, since 1/1/2016.
        t = 86400*(now - datenum('1/1/2016'));
    end

    function finalize_graphics(thumb)
        if thumb
           axis on
        else
           close
        end
    end
        
end
