function roman_clock(~)
    % Roman_clock.  Model RI-XVII.  Roman Industries Model 17.

    clf
    set(gcf, ...
        'color','w', ...
        'numbertitle','off', ...
        'menubar','none', ...
        'name','roman_clock', ...
        'inverthardcopy','off')
    shg

    % Frame
    uicontrol('style','frame', ...
            'units','normalized', ...
            'position',[.25 .10 .50 .80], ...
            'background',[.9 .9 .9]);

    % Six little windows
    w = zeros(1,6);
    for k = 1:6
        pos = [.36 .82-k*.10 .28 .07];
        w(k) = uicontrol('style','toggle', ...
            'units','normalized', ...
            'position',pos, ...
            'background','white', ...
            'fontname','courier', ...
            'fontweight','bold', ...
            'fontsize',16, ...
            'string',' ');
    end

    % exit button
    exitus = uicontrol('style','toggle', ...
            'units','normalized', ...
            'position',[.84 .02 .14 .07], ...
            'background','white', ...
            'fontsize',12, ...
            'fontweight','bold', ...
            'string','exitus');
    
    % Read and display MATLAB clock every second
    while ~get(exitus,'value')
        t = fix(clock);
        for k = 1:6
            if get(w(k),'value') == 0
                s = char(roman(t(k)));
            else
                s = int2str(t(k));
            end
            set(w(k),'string',s)
        end
        pause(0.999)
    end

    close
end  % roman_clock
